token: ionvif_token
onvif:
  netif: wlp8s0
  server-port: 8080
  rtsp-port: 8554
  profile:
    MainProfileToken: MainVideo.mkv
    SubProfileToken: SubVideo.mkv
bind:
  ionvif: tcp://127.0.0.1:3010
connect:
  iconfig: tcp://127.0.0.1:3000
